import type { MobileApiCase } from "./types";

/**
 * APIs consumed by divine_app (Flutter).
 * Sync with: divine_app/lib/core/constants/api_endpoints.dart + repository usage.
 *
 * Path params use placeholders resolved in run-smoke.ts:
 * :villaId :parcelId :pollId :visitorId :id etc.
 */
export const MOBILE_API_CASES: MobileApiCase[] = [
  // ── Public ──────────────────────────────────────────────────────────
  {
    name: "app version check",
    method: "GET",
    path: "/public/app-version",
    roles: ["public"],
    expect: [200],
    query: { platform: "ANDROID" },
  },
  {
    name: "public societies",
    method: "GET",
    path: "/public/societies",
    roles: ["public"],
    expect: [200],
  },

  // ── Resident — home & profile ───────────────────────────────────────
  { name: "resident dashboard", method: "GET", path: "/residents/dashboard", roles: ["resident"], expect: [200] },
  { name: "resident profile", method: "GET", path: "/residents/me", roles: ["resident"], expect: [200] },
  { name: "resident payment methods", method: "GET", path: "/residents/payment-methods", roles: ["resident"], expect: [200] },
  { name: "active banners", method: "GET", path: "/banners/active/list", roles: ["resident"], expect: [200] },
  { name: "vendors", method: "GET", path: "/vendors", roles: ["resident"], expect: [200] },
  { name: "security contacts", method: "GET", path: "/residents/security-contacts", roles: ["resident"], expect: [200] },
  { name: "community directory", method: "GET", path: "/residents/community-directory", roles: ["resident"], expect: [200] },

  // ── Resident — maintenance & billing ────────────────────────────────
  { name: "maintenance dashboard", method: "GET", path: "/residents/maintenance-dashboard", roles: ["resident"], expect: [200] },
  { name: "maintenance pending", method: "GET", path: "/residents/maintenance-pending", roles: ["resident"], expect: [200] },
  { name: "outstanding dues", method: "GET", path: "/residents/outstanding-dues", roles: ["resident"], expect: [200] },
  { name: "my maintenance", method: "GET", path: "/residents/my-maintenance", roles: ["resident"], expect: [200] },
  { name: "billing financial years", method: "GET", path: "/v1/financial-years", roles: ["resident", "admin"], expect: [200] },
  {
    name: "billing cycle context",
    method: "GET",
    path: "/v1/billing-cycles/context",
    roles: ["resident", "admin"],
    expect: [200, 400, 404],
    query: { billingCycleId: ":billingCycleId" },
    optional: true,
  },
  {
    name: "billing cycles current",
    method: "GET",
    path: "/v1/cycles/current",
    roles: ["resident", "admin"],
    expect: [200, 400, 404],
    query: { societyId: ":societyId" },
  },
  {
    name: "billing cycles for year",
    method: "GET",
    path: "/v1/billing-cycles",
    roles: ["resident", "admin"],
    expect: [200, 400],
    query: { financialYearId: ":financialYearId" },
    optional: true,
  },
  { name: "upi config", method: "GET", path: "/residents/upi-config", roles: ["resident"], expect: [200] },
  { name: "my upi payments", method: "GET", path: "/residents/my-upi-payments", roles: ["resident"], expect: [200] },

  // ── Resident — visitors & gate ──────────────────────────────────────
  { name: "my visitors", method: "GET", path: "/residents/my-visitors", roles: ["resident"], expect: [200] },
  { name: "visitor approval requests", method: "GET", path: "/residents/visitor-approval-requests", roles: ["resident"], expect: [200] },
  {
    name: "visitor approval detail",
    method: "GET",
    path: "/residents/visitor-approval-requests/:visitorId",
    roles: ["resident"],
    expect: [200, 404],
    optional: true,
  },
  { name: "pre-approved visitors", method: "GET", path: "/residents/my-pre-approved-visitors", roles: ["resident"], expect: [200] },

  // ── Resident — parcels, amenities, vehicles ─────────────────────────
  { name: "my parcels", method: "GET", path: "/residents/my-parcels", roles: ["resident"], expect: [200] },
  { name: "parcels pending", method: "GET", path: "/residents/parcels-pending", roles: ["resident"], expect: [200] },
  { name: "my amenities", method: "GET", path: "/residents/my-amenities", roles: ["resident"], expect: [200] },
  { name: "my bookings", method: "GET", path: "/residents/my-bookings", roles: ["resident"], expect: [200] },
  { name: "my vehicles", method: "GET", path: "/residents/my-vehicles", roles: ["resident"], expect: [200] },
  { name: "my vehicle log", method: "GET", path: "/residents/my-vehicle-log", roles: ["resident"], expect: [200] },
  { name: "my staff", method: "GET", path: "/residents/my-staff", roles: ["resident"], expect: [200] },

  // ── Resident — complaints, SOS, content ─────────────────────────────
  { name: "my complaints", method: "GET", path: "/residents/my-complaints", roles: ["resident"], expect: [200] },
  { name: "my sos list", method: "GET", path: "/residents/my-sos", roles: ["resident"], expect: [200] },
  { name: "sos active", method: "GET", path: "/residents/sos/active", roles: ["resident"], expect: [200, 404] },
  { name: "my notices", method: "GET", path: "/residents/my-notices", roles: ["resident"], expect: [200] },
  { name: "my documents", method: "GET", path: "/residents/my-documents", roles: ["resident"], expect: [200] },
  { name: "my polls", method: "GET", path: "/residents/my-polls", roles: ["resident"], expect: [200] },
  { name: "society expenses", method: "GET", path: "/residents/society-expenses", roles: ["resident"], expect: [200] },
  { name: "expense categories", method: "GET", path: "/residents/society-expenses/categories", roles: ["resident"], expect: [200] },
  {
    name: "expense detail",
    method: "GET",
    path: "/residents/society-expenses/:expenseId",
    roles: ["resident"],
    expect: [200, 404],
    optional: true,
  },
  { name: "my family", method: "GET", path: "/residents/my-family", roles: ["resident"], expect: [200] },
  { name: "emergency contacts", method: "GET", path: "/residents/emergency-contacts", roles: ["resident"], expect: [200] },
  { name: "water supply requests", method: "GET", path: "/residents/water-requests", roles: ["resident"], expect: [200] },
  { name: "special projects", method: "GET", path: "/residents/special-projects", roles: ["resident"], expect: [200] },
  {
    name: "special project detail",
    method: "GET",
    path: "/residents/special-projects/:specialProjectId",
    roles: ["resident"],
    expect: [200, 404],
    optional: true,
  },
  { name: "notifications inbox", method: "GET", path: "/notifications", roles: ["resident", "guard", "admin"], expect: [200] },
  {
    name: "notifications legacy fallback",
    method: "GET",
    path: "/residents/my-notifications",
    roles: ["resident"],
    expect: [200, 404],
    optional: true,
  },

  // ── Resident — utilities (shared with admin reads) ──────────────────
  { name: "water supply status", method: "GET", path: "/water-supply/status", roles: ["resident", "guard", "admin"], expect: [200] },
  { name: "water supply events", method: "GET", path: "/water-supply/events", roles: ["resident", "admin"], expect: [200] },
  { name: "garbage collection active", method: "GET", path: "/garbage-collection/active", roles: ["resident", "guard", "admin"], expect: [200] },
  { name: "garbage collection history", method: "GET", path: "/garbage-collection/history", roles: ["resident"], expect: [200] },

  // ── Guard — dashboard & ops ─────────────────────────────────────────
  { name: "guard dashboard", method: "GET", path: "/guards/my-dashboard", roles: ["guard"], expect: [200] },
  { name: "guard my gate", method: "GET", path: "/guards/my-gate", roles: ["guard"], expect: [200, 404] },
  { name: "guard my shifts", method: "GET", path: "/guards/my-shifts", roles: ["guard"], expect: [200] },
  { name: "guard active alerts", method: "GET", path: "/guards/active-alerts", roles: ["guard"], expect: [200] },
  { name: "guard my visitors", method: "GET", path: "/guards/my-visitors", roles: ["guard"], expect: [200] },
  { name: "guard pending visitors", method: "GET", path: "/guards/pending-visitors", roles: ["guard"], expect: [200] },
  { name: "guard residents directory", method: "GET", path: "/guards/residents-directory", roles: ["guard"], expect: [200] },
  { name: "guard pre-approved entries", method: "GET", path: "/guards/pre-approved-entries", roles: ["guard"], expect: [200] },
  { name: "society villas (guard picker)", method: "GET", path: "/villas", roles: ["guard", "admin"], expect: [200] },

  // ── Guard — parcels & patrols ───────────────────────────────────────
  { name: "guard parcels pending", method: "GET", path: "/guards/parcels-pending", roles: ["guard"], expect: [200] },
  { name: "guard my parcels today", method: "GET", path: "/guards/my-parcels", roles: ["guard"], expect: [200] },
  { name: "guard my patrols", method: "GET", path: "/guards/my-patrols", roles: ["guard"], expect: [200] },
  { name: "guard patrols today", method: "GET", path: "/guards/patrols-today", roles: ["guard"], expect: [200] },
  { name: "guard gate vehicles today", method: "GET", path: "/guards/gate-vehicle/today", roles: ["guard"], expect: [200] },
  { name: "guard checklist", method: "GET", path: "/guards/checklist", roles: ["guard"], expect: [200] },

  // ── Admin mobile — dashboard & ops ──────────────────────────────────
  { name: "admin visitors", method: "GET", path: "/visitors", roles: ["admin"], expect: [200] },
  { name: "admin parcels", method: "GET", path: "/parcels", roles: ["admin"], expect: [200] },
  { name: "admin complaints", method: "GET", path: "/complaints", roles: ["admin"], expect: [200] },
  { name: "admin financial dashboard", method: "GET", path: "/maintenance-management/financial-dashboard", roles: ["admin"], expect: [200] },
  { name: "maintenance outstanding dues", method: "GET", path: "/maintenance-management/outstanding-dues", roles: ["admin"], expect: [200] },
  {
    name: "maintenance collection financial years",
    method: "GET",
    path: "/maintenance-management/collection/financial-years",
    roles: ["admin"],
    expect: [200],
  },
  {
    name: "maintenance collection cycles",
    method: "GET",
    path: "/maintenance-management/collection/financial-years/:financialYearId/cycles",
    roles: ["admin"],
    expect: [200, 404],
    optional: true,
  },
  {
    name: "maintenance villa history",
    method: "GET",
    path: "/maintenance-management/villa-history/:villaId",
    roles: ["admin"],
    expect: [200, 404],
    optional: true,
  },
  { name: "resident management overview", method: "GET", path: "/resident-management/overview", roles: ["admin"], expect: [200] },
  { name: "resident management statistics", method: "GET", path: "/resident-management/statistics", roles: ["admin"], expect: [200] },
  { name: "complaint analytics summary", method: "GET", path: "/complaint-analytics/summary", roles: ["admin"], expect: [200] },
  { name: "complaint analytics by category", method: "GET", path: "/complaint-analytics/by-category", roles: ["admin"], expect: [200] },
  { name: "complaint analytics pending", method: "GET", path: "/complaint-analytics/pending-list", roles: ["admin"], expect: [200] },
  { name: "complaint analytics trend", method: "GET", path: "/complaint-analytics/trend", roles: ["admin"], expect: [200] },
  { name: "gate analytics overview", method: "GET", path: "/gate-analytics/overview", roles: ["admin"], expect: [200] },
  { name: "gate analytics visitor stats", method: "GET", path: "/gate-analytics/visitor-statistics", roles: ["admin"], expect: [200] },
  { name: "gate analytics peak hours", method: "GET", path: "/gate-analytics/peak-hours", roles: ["admin"], expect: [200] },
  { name: "gate analytics daily trend", method: "GET", path: "/gate-analytics/daily-trend", roles: ["admin"], expect: [200] },
  { name: "water analytics overview", method: "GET", path: "/water-supply-analytics/overview", roles: ["admin"], expect: [200] },
  { name: "water analytics daily usage", method: "GET", path: "/water-supply-analytics/daily-usage", roles: ["admin"], expect: [200] },
  { name: "water analytics hourly", method: "GET", path: "/water-supply-analytics/hourly-pattern", roles: ["admin"], expect: [200] },
  { name: "water analytics gate perf", method: "GET", path: "/water-supply-analytics/gate-performance", roles: ["admin"], expect: [200] },
  { name: "parking overview", method: "GET", path: "/parking-management/overview", roles: ["admin"], expect: [200] },
  { name: "parking slot analysis", method: "GET", path: "/parking-management/slot-analysis", roles: ["admin"], expect: [200] },
  { name: "admin vehicles", method: "GET", path: "/vehicles", roles: ["admin"], expect: [200] },
  { name: "admin gates", method: "GET", path: "/gates", roles: ["admin"], expect: [200] },
  { name: "water requests pending", method: "GET", path: "/water-supply/requests/pending", roles: ["admin"], expect: [200] },
  { name: "water supply history", method: "GET", path: "/water-supply/history", roles: ["admin"], expect: [200] },
  { name: "garbage collection events", method: "GET", path: "/garbage-collection/events", roles: ["admin"], expect: [200] },
  { name: "admin sos alerts", method: "GET", path: "/sos-alerts", roles: ["admin"], expect: [200] },
  { name: "admin sos active", method: "GET", path: "/sos-alerts/active", roles: ["admin"], expect: [200] },
  { name: "admin sos stats", method: "GET", path: "/sos-alerts/stats", roles: ["admin"], expect: [200] },
  { name: "admin guard shifts", method: "GET", path: "/guard-shifts", roles: ["admin"], expect: [200] },
  { name: "admin guard patrols", method: "GET", path: "/guard-patrols", roles: ["admin"], expect: [200] },
  { name: "admin polls", method: "GET", path: "/polls", roles: ["admin"], expect: [200] },
  { name: "admin staff", method: "GET", path: "/staff", roles: ["admin"], expect: [200] },
  { name: "admin amenities", method: "GET", path: "/amenities", roles: ["admin"], expect: [200] },
  { name: "admin bank accounts", method: "GET", path: "/bank-accounts", roles: ["admin"], expect: [200] },
  { name: "admin expenses", method: "GET", path: "/expenses", roles: ["admin"], expect: [200] },
  { name: "admin expense categories", method: "GET", path: "/expenses/categories", roles: ["admin"], expect: [200] },
  { name: "admin notices", method: "GET", path: "/notices", roles: ["admin"], expect: [200] },
  { name: "admin users", method: "GET", path: "/users", roles: ["admin"], expect: [200] },
  { name: "admin invitations", method: "GET", path: "/invitations", roles: ["admin"], expect: [200] },
  { name: "society settings", method: "GET", path: "/society-settings", roles: ["admin"], expect: [200] },
  { name: "reconciliation summary", method: "GET", path: "/reconciliation/summary", roles: ["admin"], expect: [200] },
  { name: "reconciliation alerts", method: "GET", path: "/reconciliation/alerts", roles: ["admin"], expect: [200] },
  { name: "admin upi pending", method: "GET", path: "/upi-payments/pending", roles: ["admin"], expect: [200] },
  { name: "admin upi stats", method: "GET", path: "/upi-payments/stats", roles: ["admin"], expect: [200] },
  { name: "admin special projects", method: "GET", path: "/special-projects", roles: ["admin"], expect: [200] },
  { name: "incidents list", method: "GET", path: "/incidents", roles: ["admin", "guard"], expect: [200] },
  { name: "export villas csv", method: "GET", path: "/export/villas-csv", roles: ["admin"], expect: [200, 400] },
  { name: "export residents csv", method: "GET", path: "/export/residents-csv", roles: ["admin"], expect: [200, 400] },
];

/** Safe POST/PATCH mutations — must not return 500 */
export const MOBILE_API_MUTATION_CASES: MobileApiCase[] = [
  {
    name: "guard parcel received (no description)",
    method: "POST",
    path: "/guards/parcel-received",
    roles: ["guard"],
    expect: [201],
    body: {
      villaId: ":villaId",
      deliveryService: "SmokeTest",
    },
  },
  {
    name: "auth logout",
    method: "POST",
    path: "/auth/logout",
    roles: ["resident"],
    expect: [204],
    body: {},
  },
];
